### ISSUE TITLE
Code refactoring & docs and Token logos

### ISSUE THREAD

**Issue by JonathonDunford** [Agorex-io/Tokens#8]
<a href="https://github.com/mrmm"><img src="https://avatars0.githubusercontent.com/u/796467?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mrmm](https://github.com/mrmm)**
_Monday Feb 26, 2018 at 23:16 GMT_
_Originally opened as https://github.com/forkdelta/tokenbase/pull/274_

----

Code formatting and documentation.

----

_**[mrmm](https://github.com/mrmm)** included the following code: https://github.com/forkdelta/tokenbase/pull/274/commits_

**Comment by JonathonDunford** [comment]
<a href="https://github.com/mrmm"><img src="https://avatars0.githubusercontent.com/u/796467?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mrmm](https://github.com/mrmm)**
_Tuesday Feb 27, 2018 at 01:04 GMT_

----

Added Tokens logos as mentioned in forkdelta/forkdelta.github.io#81.

### YAML file
The following example shows the added `logos` field in YAML file:
```
---

addr: '0x9294c0be711473f24de4441ff2de0773bfd96eae'
decimals: 18
description: >-
  # The following options were found                                                                       #
  # You may need to edit them and you MUST delete commented lines                                          #
  # From the website: description meta tag                                                                 #
  ArcBlock
links:
- Facebook: https://www.facebook.com/arcblock.io/
- Github: https://github.com/arcblock
- Instagram: https://www.instagram.com/arcblock/
- Linkedin: https://www.linkedin.com/in/flaviencharlon
- Linkedin: https://www.linkedin.com/in/jiaxi-lin-a536133/
- Linkedin: https://www.linkedin.com/in/violin-wang-b81a6673/
- Linkedin: https://www.linkedin.com/in/cartwrightx/
- Linkedin: https://www.linkedin.com/in/jeancheninchina
- Linkedin: https://www.linkedin.com/in/robertmao
- Linkedin: https://www.linkedin.com/in/justin-tomboulian-69b61919/
- Linkedin: https://www.linkedin.com/company/18355951/
- Linkedin: https://www.linkedin.com/in/wallin
- Linkedin: https://www.linkedin.com/in/huishen-cui-7254b362/
- Linkedin: https://www.linkedin.com/in/lawrencelerner/
- Linkedin: https://www.linkedin.com/in/maggie-wu-164a0797/
- Linkedin: https://www.linkedin.com/in/saldhanani/
- Reddit: https://www.reddit.com/r/arcblock/
- Telegram: https://t.me/ArcBlock
- Twitter: https://twitter.com/ArcBlock_io
- Website: https://www.arcblock.io/
- Whitepaper: ADD OR DELETE LINE
- Bitcointalk: ADD OR DELETE LINE
- Blog: ADD OR DELETE LINE
logos:
  default: https://www.arcblock.io/images/favicons/apple-touch-icon.png
  md: https://www.arcblock.io/images/favicons/apple-touch-icon.png
  sizes:
  - 32x32: https://www.arcblock.io/images/favicons/favicon-32x32.png
  - 16x16: https://www.arcblock.io/images/favicons/favicon-16x16.png
name: ArcBlock
symbol: ABT
```
### Possible sub-fields 
**default** the best resolution found for the token logo
**favicon** the favicon scrapped from the website (if exists)
**md** medium size token logo
**sizes** list of the different sizes scraped from the website

**Comment by JonathonDunford** [comment]
<a href="https://github.com/mrmm"><img src="https://avatars0.githubusercontent.com/u/796467?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mrmm](https://github.com/mrmm)**
_Wednesday Feb 28, 2018 at 11:05 GMT_

----

Past updates:

- Delete `sizes` sub-field from `logos` field.
- Scrape logos by priority from CoinMarketCap, Twitter and token official website.

The new format is :
```
addr: '0x827d41446a2cb012d3011b94f525d6c46b32866d'
decimals: 9
description: >-
  FILL ME IN
links:
- Facebook: https://www.facebook.com/OceanSafe-1576498739103338/
- Twitter: https://twitter.com/OceanSafeCoin
- Website: http://oceansafe.io
- Reddit: ADD OR DELETE LINE
- Bitcointalk: ADD OR DELETE LINE
- Whitepaper: ADD OR DELETE LINE
- Telegram: ADD OR DELETE LINE
- Blog: ADD OR DELETE LINE
logos:
  default: https://pbs.twimg.com/profile_images/930178730751905792/d3qhLKJn_200x200.jpg
  hd: https://pbs.twimg.com/profile_images/930178730751905792/d3qhLKJn_400x400.jpg
  icon: https://pbs.twimg.com/profile_images/930178730751905792/d3qhLKJn_normal.jpg
  md: https://pbs.twimg.com/profile_images/930178730751905792/d3qhLKJn_200x200.jpg
  sd: https://pbs.twimg.com/profile_images/930178730751905792/d3qhLKJn_bigger.jpg
name: OceanSafe Coin
symbol: OSC
```
cc @freeatnet @JonathonDunford review needed, thanks.
